#!/bin/sh

LOCAL_IP=$(ip addr show enp5s0 | grep '\<inet\>' | tr -s ' ' | cut -d ' ' -f3)
if [${LOCAL_IP} == ""]; then
    LOCAL_IP=$(ip addr show wlp4s0 | grep '\<inet\>' | tr -s ' ' | cut -d ' ' -f3)
    echo ${LOCAL_IP%/*}
else
    echo ${LOCAL_IP%/*}
fi;
